name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List file
        run: |
           pwd
           ls
      - name: simple JS Actions
        uses: actions/hello-world-javascript-action@v1
        id: greet
        with:
          who-to-greet: AmrBanna

      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}"
